openapi: 3.0.3
info:
  title: API de Gestion des Tâches de Roadtrip
  description: API REST pour la gestion des listes de tâches associées aux roadtrips
  version: 1.0.0
  contact:
    name: Support API
    email: support@monpetitroadtrip.com

servers:
  - url: http://localhost:3000
    description: Serveur de développement

security:
  - bearerAuth: []

paths:
  /roadtrips/{roadtripId}/tasks:
    get:
      summary: Récupère toutes les tâches d'un roadtrip
      tags: [Tasks]
      parameters:
        - name: roadtripId
          in: path
          required: true
          schema:
            type: string
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, in_progress, completed, cancelled]
        - name: category
          in: query
          schema:
            type: string
            enum: [preparation, booking, packing, documents, transport, accommodation, activities, health, finances, communication, other]
        - name: priority
          in: query
          schema:
            type: string
            enum: [low, medium, high, urgent]
        - name: assignedTo
          in: query
          schema:
            type: string
        - name: sortBy
          in: query
          schema:
            type: string
            default: order
        - name: sortOrder
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: asc
        - name: includeCompleted
          in: query
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: Liste des tâches avec statistiques
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  stats:
                    $ref: '#/components/schemas/TaskStats'

    post:
      summary: Crée une nouvelle tâche
      tags: [Tasks]
      parameters:
        - name: roadtripId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTaskRequest'
      responses:
        '201':
          description: Tâche créée avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /roadtrips/{roadtripId}/tasks/{taskId}:
    get:
      summary: Récupère une tâche spécifique
      tags: [Tasks]
      parameters:
        - name: roadtripId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Détails de la tâche
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

    put:
      summary: Met à jour une tâche
      tags: [Tasks]
      parameters:
        - name: roadtripId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
      responses:
        '200':
          description: Tâche mise à jour
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

    delete:
      summary: Supprime une tâche
      tags: [Tasks]
      parameters:
        - name: roadtripId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tâche supprimée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  deletedTaskId:
                    type: string

  /roadtrips/{roadtripId}/tasks/{taskId}/toggle-completion:
    patch:
      summary: Bascule le statut de completion d'une tâche
      tags: [Tasks]
      parameters:
        - name: roadtripId
          in: path
          required: true
          schema:
            type: string
        - name: taskId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Statut de tâche basculé
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'

  /roadtrips/{roadtripId}/tasks/reorder:
    patch:
      summary: Réorganise l'ordre des tâches
      tags: [Tasks]
      parameters:
        - name: roadtripId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                taskOrders:
                  type: array
                  items:
                    type: object
                    properties:
                      taskId:
                        type: string
                      order:
                        type: number
      responses:
        '200':
          description: Tâches réorganisées avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'

  /roadtrips/{roadtripId}/tasks/generate-defaults:
    post:
      summary: Génère des tâches prédéfinies pour un roadtrip
      tags: [Tasks]
      parameters:
        - name: roadtripId
          in: path
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Tâches prédéfinies créées
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  count:
                    type: number

  /roadtrips/{roadtripId}/tasks/generate-ai:
    post:
      summary: Génère des tâches intelligentes personnalisées pour un roadtrip en utilisant l'IA
      tags: [Tasks]
      parameters:
        - name: roadtripId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                replace:
                  type: boolean
                  description: Si true, les tâches existantes seront remplacées
      responses:
        '201':
          description: Tâches générées par IA
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  count:
                    type: number
        '400':
          description: Des tâches existent déjà pour ce roadtrip
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  existingTasksCount:
                    type: number

  /roadtrips/{roadtripId}/tasks/generate-ai-async:
    post:
      summary: Lance un job asynchrone de génération de tâches intelligentes personnalisées pour un roadtrip
      tags: [Tasks]
      parameters:
        - name: roadtripId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                replace:
                  type: boolean
                  description: Si true, les tâches existantes seront remplacées
      responses:
        '202':
          description: Job de génération lancé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  jobId:
                    type: string
                  status:
                    type: string
                    enum: [pending, processing, completed, failed]
        '400':
          description: Des tâches existent déjà pour ce roadtrip
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  existingTasksCount:
                    type: number
        '409':
          description: Un job est déjà en cours pour ce roadtrip
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string
                  jobId:
                    type: string
                  status:
                    type: string

  /roadtrips/{roadtripId}/tasks/jobs/{jobId}:
    get:
      summary: Récupère le statut d'un job asynchrone de génération de tâches
      tags: [Tasks]
      parameters:
        - name: roadtripId
          in: path
          required: true
          schema:
            type: string
        - name: jobId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Statut du job récupéré avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  jobId:
                    type: string
                  status:
                    type: string
                    enum: [pending, processing, completed, failed]
                  createdAt:
                    type: string
                    format: date-time
                  completedAt:
                    type: string
                    format: date-time
                  taskCount:
                    type: number
                  tasks:
                    type: array
                    items:
                      $ref: '#/components/schemas/Task'
                  error:
                    type: string
        '404':
          description: Job ou roadtrip non trouvé
          content:
            application/json:
              schema:
                type: object
                properties:
                  msg:
                    type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Task:
      type: object
      properties:
        _id:
          type: string
        userId:
          type: string
        roadtripId:
          type: string
        title:
          type: string
          maxLength: 200
        description:
          type: string
          maxLength: 1000
        category:
          type: string
          enum: [preparation, booking, packing, documents, transport, accommodation, activities, health, finances, communication, other]
        priority:
          type: string
          enum: [low, medium, high, urgent]
        status:
          type: string
          enum: [pending, in_progress, completed, cancelled]
        dueDate:
          type: string
          format: date-time
          nullable: true
        completedAt:
          type: string
          format: date-time
          nullable: true
        assignedTo:
          type: string
          maxLength: 100
        estimatedDuration:
          type: number
          nullable: true
        reminderDate:
          type: string
          format: date-time
          nullable: true
        attachments:
          type: array
          items:
            type: string
        notes:
          type: string
          maxLength: 2000
        order:
          type: number
        isRecurring:
          type: boolean
        recurringPattern:
          type: string
          enum: [daily, weekly, monthly]
          nullable: true
        isOverdue:
          type: boolean
          readOnly: true
        timeRemaining:
          type: number
          nullable: true
          readOnly: true
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    CreateTaskRequest:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          maxLength: 200
        description:
          type: string
          maxLength: 1000
        category:
          type: string
          enum: [preparation, booking, packing, documents, transport, accommodation, activities, health, finances, communication, other]
          default: preparation
        priority:
          type: string
          enum: [low, medium, high, urgent]
          default: medium
        dueDate:
          type: string
          format: date-time
        assignedTo:
          type: string
          maxLength: 100
        estimatedDuration:
          type: number
        reminderDate:
          type: string
          format: date-time
        notes:
          type: string
          maxLength: 2000
        attachments:
          type: array
          items:
            type: string

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          maxLength: 200
        description:
          type: string
          maxLength: 1000
        category:
          type: string
          enum: [preparation, booking, packing, documents, transport, accommodation, activities, health, finances, communication, other]
        priority:
          type: string
          enum: [low, medium, high, urgent]
        status:
          type: string
          enum: [pending, in_progress, completed, cancelled]
        dueDate:
          type: string
          format: date-time
        assignedTo:
          type: string
          maxLength: 100
        estimatedDuration:
          type: number
        reminderDate:
          type: string
          format: date-time
        notes:
          type: string
          maxLength: 2000
        attachments:
          type: array
          items:
            type: string
        order:
          type: number

    TaskStats:
      type: object
      properties:
        total:
          type: number
        pending:
          type: number
        in_progress:
          type: number
        completed:
          type: number
        cancelled:
          type: number
        completionPercentage:
          type: number

    Error:
      type: object
      properties:
        msg:
          type: string
        error:
          type: string

tags:
  - name: Tasks
    description: Gestion des tâches de roadtrip
